filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: $ELASTICSEARCH_PASSWORD
setup.kibana:
  host: "http://kibana:5601"